dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.3.0"
compiler:
  solc:
    optimizer:
      enabled: true
      runs: 800
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0"
