dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.4.0"
  - "OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.0"
compiler:
  solc:
    optimizer:
      enabled: true
      runs: 800
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.0/contracts"
